import time

from src.config import Config
from src.data_loader import load_and_validate_transactions
from src.excel_writer import write_excel_report
from src.leakage_analysis import aggregate_leakage, flag_leakage


def main() -> None:
    start = time.time()
    cfg = Config()

    df, csv_path = load_and_validate_transactions(cfg)
    df_flagged = flag_leakage(df, cfg)

    aggregates = aggregate_leakage(df_flagged, cfg)

    excel_path = write_excel_report(df_flagged, aggregates, cfg)

    # Word 1-pager
    # Implement inline to keep project small.
    from docx import Document
    from docx.shared import Pt

    doc = Document()
    doc.add_heading("Revenue Leakage QMR — Problem → Fix → Impact", level=1)

    # Extract KPI
    kpi = aggregates["kpi"].iloc[0]
    mismatch_count = int(kpi["mismatch_count"])
    mismatch_rate = float(kpi["mismatch_rate"])
    leakage_under = float(kpi["leakage_underreported_total"])

    doc.add_paragraph(
        f"Problem: {mismatch_count} transactions were flagged as out-of-tolerance between transaction_amt and reported_amt. "
        f"Mismatch rate is {mismatch_rate:.2%}. Potential under-reported revenue total: {leakage_under:,.2f}."
    )

    doc.add_paragraph("Fix (QMR process improvements):")
    doc.add_paragraph("• Enforce automated tolerance checks at ingestion (abs + pct threshold).")
    doc.add_paragraph("• Require exception workflow for mismatched invoices (customer + invoice + currency).")
    doc.add_paragraph("• Add reconciliation controls: compare ledger booking vs reporting extraction daily.")
    doc.add_paragraph("• Track root causes: timing mismatch, currency conversion, unit/rounding differences.")

    doc.add_paragraph("Impact:")
    doc.add_paragraph(
        "• Faster detection of revenue leakage prior to month-end close. "
        "• Improved reporting accuracy and auditability with repeatable validation rules. "
        f"• Expected recovery proportional to under-reported delta (seeded mock data estimates: {leakage_under:,.2f})."
    )

    doc.add_paragraph("\nGenerated by revenue-leakage-qmr (portfolio demo).")

    doc_out = cfg.docx_output_path
    doc_out.parent.mkdir(parents=True, exist_ok=True)
    doc.save(doc_out)

    elapsed = time.time() - start
    print("Done.")
    print(f"Input CSV: {csv_path}")
    print(f"Excel QMR:  {excel_path}")
    print(f"Word doc:   {doc_out}")
    print(f"Elapsed: {elapsed:.2f}s")


if __name__ == "__main__":
    main()

